baseURL = "https://xxm404.github.io/"
title = "辛二's Blog"
languageCode = "zh-hans"
theme = "hermit"
# googleAnalytics = "UA-130696996-1"
enableRobotsTXT = true
enableEmoji = true
disqusShortname = "xxm404-github-io"
paginate = 5
rssLimit = 20
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsUseClasses  = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"
defaultContentDir = "posts"

enableGitInfo = true

# [sitemap]
#   changefreq = "weekly"
#   priority = 0.5
#   filename = "sitemap.xml"

[author]
  name = "辛二"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # gitUrl = "https://github.com/aylei/blog/commit/"

  homeSubtitle = "Reliability, Scalability, Maintainability"

  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  logoImage = "me.jpeg"
  since = "2019"
  homeFullContent = false
  rssFullContent = true
  archive-paginate = 10
  dateFormatToUse = "2006-01-02"
  moreMeta = true
  showMenuLanguageChooser = true
  showAuthorInfo = true
  toc = true
  photoswipe = true
  keywords = ["cloudnative","devops","kubernetes","golang","php","programming"]
  description = "One more!"
  [[params.social]]
    name = "twitter"
    url = ""

  [[params.social]]
    name = "github"
    url = "https://github.com/xxm404"


  [[params.social]]
    name = "email"
    url = "mailto:xinmian404@gmail.com"

[params.meta]
  description = "辛二's Blog"
  keywords = "cloudnative,devops,kubernetes,prometheus,golang,java,programming"

[menu]

  [[menu.main]]
    name = "文章"
    url = "posts/"
    weight = 10

    [[menu.main]]
    name = "关于"
    url = "about/"
    weight = 20
